services:
  postgres:
    container_name: srirejeki-postgres
    image: postgres:alpine
    env_file:
      - ./.env
    restart: unless-stopped
    volumes:
      - ./docker/volumes/postgres:/var/lib/postgresql/data:Z
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      TZ: Asia/Jakarta
    # ports:
    #   - 5432:5432
    networks:
      - srirejeki-network

networks:
  srirejeki-network:
    name: srirejeki-network
