###
### BUILD
###
FROM golang:alpine AS build
ADD . /go/src/srirejeki
WORKDIR /go/src/srirejeki
RUN go mod tidy
RUN go build -o /app/srirejeki-backend

###
### DEPLOY
###
FROM alpine:latest
COPY --from=build /app/srirejeki-backend /app/srirejeki-backend
WORKDIR /app
EXPOSE 8080
ENTRYPOINT [ "/app/srirejeki-backend" ]